AWS_ACCESS_KEY_ID: "AKIAJOGZEH5DJ3CKWNQA"
AWS_SECRET_ACCESS_KEY: "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"
development:
  SENDGRID_USERNAME: "app20414167@heroku.com"
  SENDGRID_PASSWORD: "isn5ne8l"
  AWS_BUCKET: "ben-bloccit-development"
  FACEBOOK_ID: "417515261684587"
  FACEBOOK_SECRET: "9fa4599c7d8cbb2da958b6a6cd64d7d8"
production:
  AWS_BUCKET: "ben-bloccit-production"
  # FACEBOOK_ID: 
  # FACEBOOK_SECRET: 
